version: "3"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8096:8096
    volumes:
      - /opt/config/jellyfin:/config
      - /opt/cache/jellyfin:/cache
      - /downloads:/downloads
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - /opt/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - /opt/config/radarr:/config
      - /downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - /opt/config/sonarr:/config
      - /downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  jproxy:
    image: luckypuppy514/jproxy:latest
    container_name: jproxy
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 8117:8117
    volumes:
      - /opt/data/jproxy:/app/database
    restart: unless-stopped
