version: "3"

services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=501
      - PUID=20
      - TZ=Asia/Shanghai
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - ~/homelab/opt/config/qbit:/config
      - ~/homelab/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=501
      - PUID=20
      - TZ=Etc/UTC
    volumes:
      - ~/homelab/opt/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=501
      - PUID=20
      - TZ=Asia/Shanghai
    volumes:
      - ~/homelab/opt/config/radarr:/config
      - ~/homelab/downloads:/downloads

    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=501
      - PUID=20
      - TZ=Asia/Shanghai
    volumes:
      - ~/homelab/opt/config/sonarr:/config
      - ~/homelab/downloads:/downloads

    ports:
      - 8989:8989
    restart: unless-stopped
  jproxy:
    image: luckypuppy514/jproxy:latest
    container_name: jproxy
    environment:
      - PUID=501
      - PUID=20
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 8117:8117
    volumes:
      - ~/homelab/opt/data/jproxy:/app/database
    restart: unless-stopped
