version: "3"

# docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    volumes:
      - ./data/nginx-proxy-manager:/data
    network_mode: host
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - UMASK_SET=022
      - WEBUI_PORT=8686
    ports:
      - 8686:8080
    volumes:
      - /home/chao/config/qbit:/config
      - /opt/download/media:/downloads
    network_mode: host
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    volumes:
      - /home/chao/data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9443:9443
      - 8000:8000
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=error
      - TZ=Asia/Shanghai
    ports:
      - 5055:5055
    volumes:
      - /home/chao/config/jellyseer:/app/config
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /home/chao/config/jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /home/chao/config/radarr:/config
    ports:
      - 7878:7878
    restart: unless-stopped

  # 需要两个 sonarr 的同学，再添加一个sonarr容器即可，记得更改 名字和端口映射
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /home/chao/config/sonarr:/config
    ports:
      - 8989:8989
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    networks:
      - dockernet
    ports:
      - 8096:8096
    volumes:
      - /usr/share/fonts/noto-cjk:/usr/share/fonts/noto-cjk
      - /dev/dri:/dev/dri
      - /home/chao/config/jellyfin:/config
      - home/chao/cache/kellyfin:/cache
      - /home/chao/media:/media
      - /home/chao/media2:/media:ro
    restart: unless-stopped

  # 自动更新docker镜像，可选，建议开启
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 7200
    restart: unless-stopped
