version: "3"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # root 硬解码
    environment:
      - PUID=501
      - PUID=20
      - TZ=Asia/Shanghai
    ports:
      - 8096:8096
    volumes:
      - ~/homelab/opt/config/jellyfin:/config
      - ~/homelab/opt/cache/jellyfin:/cache
      - ~/homelab/downloads:/downloads
    restart: unless-stopped
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=error
      - TZ=Asia/Shanghai
    ports:
      - 5055:5055
    volumes:
      - ~/homelab/opt/config/jellyseerr:/app/config
    restart: unless-stopped
